### ISSUE TITLE
Error: the command training/run_experiment.py could not be found within PATH or Pipfile's [scripts]

### ISSUE THREAD

**Issue by gitfourteen** [full-stack-deep-learning/fsdl-text-recognizer-project#8]
I'm following this FSDL bootcamp with google **colab** and got these problems. I knew there are similar issues opened and some suggestions. But tried and failed in my case. Would you advise what to do in **colab**? Thanks.

### Issue description
- `pwd`
'/content/gdrive/My Drive/fsdl-text-recognizer-project'

- `!pip install pipenv`
...
Successfully installed pipenv-2018.11.26 virtualenv-16.7.2 virtualenv-clone-0.5.3

- `!pipenv install --dev`
Creating a virtualenv for this project…
Pipfile: /content/gdrive/My Drive/fsdl-text-recognizer-project/Pipfile
...

- `cd lab2_sln/`
/content/gdrive/My Drive/fsdl-text-recognizer-project/lab2_sln

- `ls`
notebooks/  readme.md  tasks/  text_recognizer/  training/

- `!pipenv run training/run_experiment.py --save '{"dataset": "EmnistDataset", "model": "CharacterModel", "network": "mlp",  "train_args": {"batch_size": 256}}'`
**Error: the command training/run_experiment.py could not be found within PATH or Pipfile's [scripts].**

**Comment by gitfourteen** [comment]
**and** 

`!pipenv run pytest -s text_recognizer/tests/test_character_predictor.py`

============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
rootdir: /content/gdrive/My Drive/fsdl-text-recognizer-project/lab2_sln, inifile:
collected 0 items / 1 errors                                                   

==================================== ERRORS ====================================
______ ERROR collecting text_recognizer/tests/test_character_predictor.py ______
ImportError while importing test module '/content/gdrive/My Drive/fsdl-text-recognizer-project/lab2_sln/text_recognizer/tests/test_character_predictor.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
text_recognizer/tests/test_character_predictor.py:4: in <module>
    from text_recognizer.character_predictor import CharacterPredictor
E   ModuleNotFoundError: No module named 'text_recognizer'
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.74 seconds ============================

**Comment by gitfourteen** [comment]
...
> * `!pipenv run training/run_experiment.py --save '{"dataset": "EmnistDataset", "model": "CharacterModel", "network": "mlp",  "train_args": {"batch_size": 256}}'`
>   **Error: the command training/run_experiment.py could not be found within PATH or Pipfile's [scripts].**

the command above is copied directly from [read.md](https://github.com/full-stack-deep-learning/fsdl-text-recognizer-project/blob/master/lab2_sln/readme.md)

No idea why they discard `python` in the commands. When correct and run, another **ModuleNotFoundError** comes.

- `!pipenv run python training/run_experiment.py '{"dataset": "EmnistDataset", "model": "CharacterModel", "network": "mlp", "network_args": {"num_layers": 8}, "train_args": {"batch_size": 128}}'`
Traceback (most recent call last):
  File "training/run_experiment.py", line 8, in <module>
    from training.util import train_model
ModuleNotFoundError: No module named 'training'

**Comment by gitfourteen** [comment]
> ...
> 
> > * `!pipenv run training/run_experiment.py --save '{"dataset": "EmnistDataset", "model": "CharacterModel", "network": "mlp",  "train_args": {"batch_size": 256}}'`
> >   **Error: the command training/run_experiment.py could not be found within PATH or Pipfile's [scripts].**
> 
> the command above is copied directly from [read.md](https://github.com/full-stack-deep-learning/fsdl-text-recognizer-project/blob/master/lab2_sln/readme.md)
> 
> No idea why they discard `python` in the commands. When correct and run, another **ModuleNotFoundError** comes.
> 
> * `!pipenv run python training/run_experiment.py '{"dataset": "EmnistDataset", "model": "CharacterModel", "network": "mlp", "network_args": {"num_layers": 8}, "train_args": {"batch_size": 128}}'`
>   Traceback (most recent call last):
>   File "training/run_experiment.py", line 8, in 
>   from training.util import train_model
>   ModuleNotFoundError: No module named 'training'
> 
> **Run equivalent sh command**
> 
> * `!pipenv run sh tasks/train_character_predictor.sh`
>   Traceback (most recent call last):
>   File "training/run_experiment.py", line 8, in 
>   from training.util import train_model
>   ModuleNotFoundError: No module named 'training'

Prefix `!PYTHONPATH='.' `will address this issue
e.g.,
 `!PYTHONPATH='.'  pipenv run sh tasks/train_character_predictor.sh`

**Comment by sachin-suresh-rapyuta** [comment]
I am running sphinx-versioning command and I get the same error. I tried prefixing the `!PYTHONPATH='.'` before and still get the same issue.

Command: `!PYTHONPATH='.' pipenv run sphinx-versioning build -r version-test docs docs/_build/html`.

Have you managed to fix this?
